#! /bin/bash

#########################
# Script configuration  #
#######################################################

# Measurement configuration
SENSORS_PERIOD=10
# Not activate by default
PARKING_PERIOD=

# Meshblu device broker configuration 
BROKER_URL=""
GATEWAY_UUID=""

# Github repository configuration
GIT_REPO_URL="https://github.com/emberscity"
GIT_REPO_NAME="iot-lab"
EMBERS_DIR="${HOME}/embers"
GIT_EMBERS_DIR="${EMBERS_DIR}/${GIT_REPO_NAME}"

#######################################################


if [ -z "${EXP_ID}" ]; then
    exit 1
fi
readonly SCRIPT_LOG_FILE="${EMBERS_DIR}/${EXP_ID}.log"

SCRIPT_SERIAL="${GIT_EMBERS_DIR}/serial_sensors.py"
SCRIPT_ARGS="-i ${EXP_ID}"
SCRIPT_ARGS+=" --broker-url ${BROKER_URL} --gateway-uuid ${GATEWAY_UUID}"

git_clone_embers() {
    if [ ! -d "${GIT_EMBERS_DIR}" ]; then
        mkdir -p ${GIT_EMBERS_DIR}
        git clone ${GIT_REPO_URL}/${GIT_REPO_NAME}.git ${GIT_EMBERS_DIR} 
    fi
}

git_pull_embers() {
    cd ${GIT_EMBERS_DIR} && git pull ; cd -
}

launch_script() {
    local script_args=${SCRIPT_ARGS}

    if [ -n "${SENSORS_PERIOD}" ]; then
       script_args+=" --sensors-period ${SENSORS_PERIOD}"
    fi
    if [ -n "${PARKING_PERIOD}" ]; then
       script_args+=" --parking-period ${PARKING_PERIOD}"   
    fi 

    # Force stdin, stdout and stderr to be totally unbuffered
    python -u ${SCRIPT_SERIAL} ${script_args} >> ${SCRIPT_LOG_FILE} 2>&1
}

git_clone_embers
git_pull_embers
launch_script
